/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FetchTestImport } from './routes/fetchTest'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const FetchTestRoute = FetchTestImport.update({
  path: '/fetchTest',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/fetchTest': {
      id: '/fetchTest'
      path: '/fetchTest'
      fullPath: '/fetchTest'
      preLoaderRoute: typeof FetchTestImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({ IndexRoute, FetchTestRoute })

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/fetchTest"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/fetchTest": {
      "filePath": "fetchTest.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
